apiVersion: v1
kind: Pod
metadata:
  name: ruxos-container
  namespace: default
spec:
  automountServiceAccountToken: false
  containers:
  - name: ruxos-vm
    image: hvisor-ruxos
    command: ["sleep"]
    args: ["infinity"]
  nodeSelector:
    kubernetes.io/hostname: nxp-agent

