apiVersion: v1
kind: Pod
metadata:
  name: linux-container
  namespace: default
spec:
  automountServiceAccountToken: false
  containers:
  - name: linux-vm
    image: hvisor-linux
    command: ["sleep"]
    args: ["infinity"]
    livenessProbe:
      exec:
        command: ["/bin/sh","-c","echo probe-ok"]
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 2
  nodeSelector:
    kubernetes.io/hostname: nxp-agent